import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ActiveChannels from '@/components/ActiveChannels'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p style={{ display: 'none' }}>
            Get started by editing&nbsp;
            <code className={styles.code}></code>
          </p>
          <div>
            <a
              href="#"
            >
              By Ajay Chauhan
            </a>
          </div>
        </div>

        <div className={styles.center}>
          Graphql Api
          <div className={styles.thirteen}>
            Shop App
          </div>
        </div>

        <div className={styles.grid}>
          <ActiveChannels />
        </div>
      </main>
    </>
  )
}
